<?php include 'inc/session.php'; ?>
<?php if($adminSorgu->rowCount()> '0'  ) {?>
    <?php
    //todo ioncube
    if(isset($_GET['process'])){
        $s = $_GET['process'];
        switch($s){
            case 'cache_clear';
                require_once("inc/modules/cache/clear.php");
                break;
            case 'logout';
                require_once("inc/modules/admin/logout.php");
                break;
            case 'todopost';
                require_once("inc/modules/todo/todopost.php");
                break;
            case 'todo_delete';
                require_once("inc/modules/todo/todo_delete.php");
                break;
            case 'bell_sound_switch';
                require_once("inc/modules/admin/sound_switch.php");
                break;
            case 'settings_update';
                require_once("inc/modules/settings/settings_update.php");
                break;
            case 'favicon_update';
                require_once("inc/modules/settings/favicon.php");
                break;
            case 'panel_settings_update';
                require_once("inc/modules/settings/panel_settings_update.php");
                break;
            case 'panel_logo';
                require_once("inc/modules/settings/panel_logo.php");
                break;
            case 'admin_post';
                require_once("inc/modules/admin/admin_post.php");
                break;
            case 'permission_post';
                require_once("inc/modules/admin/admin_permission_post.php");
                break;
            case 'log_delete';
                require_once("inc/modules/log_delete.php");
                break;

            case 'lang_post';
                require_once("inc/modules/language/language_post.php");
                break;

            case 'maintenance_post';
                require_once("inc/modules/settings/maintenance_post.php");
                break;

            case 'popup_post';
                require_once("inc/modules/settings/popup_post.php");
                break;

            case 'code_post';
                require_once("inc/modules/settings/code_post.php");
                break;

            case 'cache_post';
                require_once("inc/modules/settings/cache_post.php");
                break;
            case 'print_theme_post';
                require_once("inc/modules/theme/print_theme_post.php");
                break;

            case 'theme_header_post';
                require_once("inc/modules/theme/header_post.php");
                break;

            case 'theme_mobil_post';
                require_once("inc/modules/theme/mobil_post.php");
                break;

            case 'theme_footer_post';
                require_once("inc/modules/theme/footer_post.php");
                break;

            case 'theme_catalog_post';
                require_once("inc/modules/theme/catalog_post.php");
                break;

            case 'theme_users_post';
                require_once("inc/modules/theme/users_post.php");
                break;
            case 'theme_font_post';
                require_once("inc/modules/theme/font_post.php");
                break;
            case 'theme_banner_post';
                require_once("inc/modules/theme/banners_post.php");
                break;
            case 'theme_mail_post';
                require_once("inc/modules/theme/mail_theme_post.php");
                break;
            case 'theme_cart_post';
                require_once("inc/modules/theme/cart_theme_post.php");
                break;
            case 'theme_compare_post';
                require_once("inc/modules/theme/compare_theme_post.php");
                break;
            case 'theme_contact_post';
                require_once("inc/modules/theme/contact_theme_post.php");
                break;
            case 'theme_preloader_post';
                require_once("inc/modules/theme/preloader_theme_post.php");
                break;
            case 'theme_slider_post';
                require_once("inc/modules/theme/slider_theme_post.php");
                break;
            case 'theme_story_post';
                require_once("inc/modules/theme/story_theme_post.php");
                break;
            case 'theme_modal_post';
                require_once("inc/modules/theme/modal_theme_post.php");
                break;
            case 'theme_404_post';
                require_once("inc/modules/theme/404_theme_post.php");
                break;
            case 'theme_banks_post';
                require_once("inc/modules/theme/banks_theme_post.php");
                break;
            case 'theme_ptable_post';
                require_once("inc/modules/theme/ptable_theme_post.php");
                break;
            case 'theme_services_post';
                require_once("inc/modules/theme/services_theme_post.php");
                break;
            case 'theme_blogs_post';
                require_once("inc/modules/theme/blogs_theme_post.php");
                break;
            case 'theme_enews_post';
                require_once("inc/modules/theme/enews_theme_post.php");
                break;
            case 'theme_comments_post';
                require_once("inc/modules/theme/comments_theme_post.php");
                break;
            case 'theme_counters_post';
                require_once("inc/modules/theme/counters_theme_post.php");
                break;
            case 'theme_faq_post';
                require_once("inc/modules/theme/faq_theme_post.php");
                break;
            case 'theme_videos_post';
                require_once("inc/modules/theme/videos_theme_post.php");
                break;
            case 'theme_intro_post';
                require_once("inc/modules/theme/intro_theme_post.php");
                break;
            case 'theme_gallery_post';
                require_once("inc/modules/theme/gallery_theme_post.php");
                break;
            case 'payment_settings_post';
                require_once("inc/modules/config/payment_settings_post.php");
                break;
            case 'pos_settings_post';
                require_once("inc/modules/config/pos_settings_post.php");
                break;
            case 'order_status_post';
                require_once("inc/modules/config/order_status_post.php");
                break;
            case 'commerce_settings_post';
                require_once("inc/modules/config/commerce_settings_post.php");
                break;
            case 'bank_accounts_post';
                require_once("inc/modules/config/bank_accounts_post.php");
                break;
            case 'countries_post';
                require_once("inc/modules/config/countries_post.php");
                break;
            case 'currency_post';
                require_once("inc/modules/config/currency_post.php");
                break;
            case 'delivery_settings_post';
                require_once("inc/modules/config/delivery_settings_post.php");
                break;
            case 'delivery_company_post';
                require_once("inc/modules/config/delivery_company_post.php");
                break;
            case 'installment_rate_post';
                require_once("inc/modules/config/installment_rate_post.php");
                break;
            case 'smtp_settings_post';
                require_once("inc/modules/config/smtp_settings_post.php");
                break;
            case 'sms_settings_post';
                require_once("inc/modules/config/sms_settings_post.php");
                break;
            case 'tophtml_area_post';
                require_once("inc/modules/modules/tophtml_area_post.php");
                break;
            case 'topheader_links_post';
                require_once("inc/modules/modules/topheader_links_post.php");
                break;
            case 'header_links_post';
                require_once("inc/modules/modules/header_links_post.php");
                break;
            case 'footer_links_post';
                require_once("inc/modules/modules/footer_links_post.php");
                break;
            case 'top_slider_post';
                require_once("inc/modules/modules/top_slider_post.php");
                break;
            case 'middle_slider_post';
                require_once("inc/modules/modules/middle_slider_post.php");
                break;
            case 'stories_post';
                require_once("inc/modules/modules/stories_post.php");
                break;
            case 'showcase_post';
                require_once("inc/modules/modules/showcase_post.php");
                break;
            case 'sub_navigations_post';
                require_once("inc/modules/contents/sub_navigations_post.php");
                break;
            case 'page_management_post';
                require_once("inc/modules/contents/page_management_post.php");
                break;
            case 'contract_post';
                require_once("inc/modules/contents/contract_post.php");
                break;
            case 'ptable_post';
                require_once("inc/modules/contents/ptable_post.php");
                break;
            case 'blog_post';
                require_once("inc/modules/contents/blog_post.php");
                break;
            case 'modul_comment_post';
                require_once("inc/modules/contents/modul_comment_post.php");
                break;
            case 'services_post';
                require_once("inc/modules/contents/services_post.php");
                break;
            case 'photo_gallery_post';
                require_once("inc/modules/contents/photo_gallery_post.php");
                break;
            case 'video_gallery_post';
                require_once("inc/modules/contents/video_gallery_post.php");
                break;
            case 'contact_post';
                require_once("inc/modules/contents/contact_post.php");
                break;
            case 'social_post';
                require_once("inc/modules/contents/social_post.php");
                break;
            case 'counters_post';
                require_once("inc/modules/contents/counters_post.php");
                break;
            case 'tbox_post';
                require_once("inc/modules/contents/tbox_post.php");
                break;
            case 'client_comments_post';
                require_once("inc/modules/contents/client_comments_post.php");
                break;
            case 'faq_post';
                require_once("inc/modules/contents/faq_post.php");
                break;
            case 'merchants_post';
                require_once("inc/modules/contents/merchants_post.php");
                break;
            case 'mobile_header_post';
                require_once("inc/modules/modules/mobile_header_post.php");
                break;
            case 'coupon_post';
                require_once("inc/modules/campaign/coupon_post.php");
                break;
            case 'email_list_post';
                require_once("inc/modules/campaign/email_list_post.php");
                break;
            case 'sms_list_post';
                require_once("inc/modules/campaign/sms_list_post.php");
                break;
            case 'noti_post';
                require_once("inc/modules/campaign/noti_post.php");
                break;
            case 'users_post';
                require_once("inc/modules/users/users_post.php");
                break;
            case 'ticket_post';
                require_once("inc/modules/users/ticket_post.php");
                break;
            case 'panel_notification';
                require_once("inc/modules/panel_notification.php");
                break;
            case 'order_post';
                require_once("inc/modules/orders/order_post.php");
                break;
            case 'export_post';
                require_once("inc/modules/export/export_post.php");
                break;
            case 'bank_transfer_post';
                require_once("inc/modules/orders/bank_transfer_post.php");
                break;
            case 'other_post';
                require_once("inc/modules/other_post.php");
                break;
            case 'catalog_post';
                require_once("inc/modules/catalog/catalog_post.php");
                break;
            case 'catalog_post2';
                require_once("inc/modules/catalog/catalog_post2.php");
                break;
            case 'brand_edit';
                require_once("inc/modules/catalog/brand_edit.php");
                break;
            case 'multi_update';
                require_once("inc/modules/catalog/multi_update.php");
                break;
            case 'product_export_post';
                require_once("inc/modules/entegration/product_export_post.php");
                break;
            case 'email_import_post';
                require_once("inc/modules/entegration/email_import_post.php");
                break;
            case 'email_laststep_post';
                require_once("inc/modules/entegration/email_list_import_process_step_post.php");
                break;

            case 'gsm_import_post';
                require_once("inc/modules/entegration/gsm_import_post.php");
                break;
            case 'gsm_laststep_post';
                require_once("inc/modules/entegration/gsm_list_import_process_step_post.php");
                break;


            case 'product_import_post';
                require_once("inc/modules/entegration/product_import_post.php");
                break;
            case 'product_laststep_post';
                require_once("inc/modules/entegration/product_import_process_step_post.php");
                break;


            case 'pazar_post';
                require_once("inc/modules/entegration/pazar/pazar_post.php");
                break;

            case 'ty_post';
                require_once("inc/modules/entegration/pazar/ty_post.php");
                break;
            case 'ty_order_services_get';
                require_once("inc/modules/entegration/pazar/ty_siparisleri_cek.php");
                break;


            case 'hb_post';
                require_once("inc/modules/entegration/pazar/hb_post.php");
                break;
            case 'hb_order_services_get';
                require_once("inc/modules/entegration/pazar/hb_siparisleri_cek.php");
                break;
        }
    }else{
        header('Location:'.$ayar['panel_url'].'404');
    }?>
    <?php
}else{
    header('Location:'.$ayar['site_url'].'404');
}
?>