<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Parasut\\API\\' => array($vendorDir . '/inpinos/php-parasut-api-v4/src'),
);
