<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitde5e6c1cb7e4dae9989856e7580ab685
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Parasut\\API\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Parasut\\API\\' => 
        array (
            0 => __DIR__ . '/..' . '/inpinos/php-parasut-api-v4/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitde5e6c1cb7e4dae9989856e7580ab685::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitde5e6c1cb7e4dae9989856e7580ab685::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitde5e6c1cb7e4dae9989856e7580ab685::$classMap;

        }, null, ClassLoader::class);
    }
}
